name: ARTIFACT

on: push

env:
  ARTIFACT_NAME: "artifact-doc"

jobs:
  artifact:
    name: Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - run: echo "Hello World at $(date)." >./out-artifact
        name: Generate
      - uses: actions/upload-artifact@v3.1.3
        name: Upload
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./out-artifact
