name: DATE_MINI

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date
  macos:
    runs-on: macos-latest
    steps:
      - run: date
  windows:
    runs-on: windows-latest
    steps:
      - run: Get-Date
  final:
    runs-on: ubuntu-latest
    needs: [ date-ubuntu, date-macos, date-windows ]
    steps:
      - run: date
