name: PYTHON

on: push

env:
  ARTIFACT_NAME: "learn-github-actions"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: actions/setup-python@v4
        name: Setup
        with:
          python-version: 3.10
      - run: python ./hello.py
        name: Run
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: actions/setup-python@v4
        name: Setup
        with:
          python-version: 3.10
      - uses: actions/upload-artifact@v3.1.3
        name: Upload
        with: 
          name: ${{ env.ARTIFACT_NAME }}
          path: .